<?php

namespace Core\Developer\Controller;

use Core\Backend\Main as BackendMain;
use Core\Utility\Controller\DefaultPlaceholder;
use Core\Utility\Main as Utility;
use Core\Container\Container;
use Core\Utility\Controller\DefaultController;
use Slim\Http\Request;
use Slim\Http\Response;

/**
 * Class FontAwesome
 *
 * it insert into the view data some font-awesome icons and run the view of that contains the list of icons
 *
 * @package Core\Developer\Controller
 */
class FontAwesome extends DefaultController
{
    private $container;
    private $title = APP_NAME . META_TITLE_SEPARATOR . 'Lista di icone fontAwesome';
    public $backend;
    public $utility;

    public $view_data;

    public function __construct(Container $container)
    {
        $this->container = $container;
        $this->backend = new BackendMain($container);
        $this->utility = new Utility();
    }

    public function __invoke(Request $request, Response $response)
    {
        $this->backend->logged_user->blockIfHasNotRole(['amministratore', 'admin', 'direzione', 'super utente']);

        $class ='fa fa-fw';
        $this->view_data['icons'] = [];
        $array = [
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use 500px\">fa-500px</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use address-book\">fa-address-book</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use address-book-o\">fa-address-book-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use address-card\">fa-address-card</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use address-card-o\">fa-address-card-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use adjust\">fa-adjust</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use adn\">fa-adn</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use align-center\">fa-align-center</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use align-justify\">fa-align-justify</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use align-left\">fa-align-left</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use align-right\">fa-align-right</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use amazon\">fa-amazon</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use ambulance\">fa-ambulance</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use american-sign-language-interpreting\">fa-american-sign-language-interpreting</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use anchor\">fa-anchor</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use android\">fa-android</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use angellist\">fa-angellist</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use angle-double-down\">fa-angle-double-down</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use angle-double-left\">fa-angle-double-left</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use angle-double-right\">fa-angle-double-right</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use angle-double-up\">fa-angle-double-up</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use angle-down\">fa-angle-down</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use angle-left\">fa-angle-left</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use angle-right\">fa-angle-right</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use angle-up\">fa-angle-up</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use apple\">fa-apple</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use archive\">fa-archive</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use area-chart\">fa-area-chart</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use arrow-circle-down\">fa-arrow-circle-down</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use arrow-circle-left\">fa-arrow-circle-left</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use arrow-circle-o-down\">fa-arrow-circle-o-down</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use arrow-circle-o-left\">fa-arrow-circle-o-left</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use arrow-circle-o-right\">fa-arrow-circle-o-right</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use arrow-circle-o-up\">fa-arrow-circle-o-up</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use arrow-circle-right\">fa-arrow-circle-right</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use arrow-circle-up\">fa-arrow-circle-up</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use arrow-down\">fa-arrow-down</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use arrow-left\">fa-arrow-left</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use arrow-right\">fa-arrow-right</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use arrow-up\">fa-arrow-up</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use arrows\">fa-arrows</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use arrows-alt\">fa-arrows-alt</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use arrows-h\">fa-arrows-h</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use arrows-v\">fa-arrows-v</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use asl-interpreting\">fa-asl-interpreting </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use assistive-listening-systems\">fa-assistive-listening-systems</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use asterisk\">fa-asterisk</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use at\">fa-at</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use audio-description\">fa-audio-description</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use automobile\">fa-automobile </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use backward\">fa-backward</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use balance-scale\">fa-balance-scale</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use ban\">fa-ban</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bandcamp\">fa-bandcamp</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bank\">fa-bank </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bar-chart\">fa-bar-chart</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bar-chart-o\">fa-bar-chart-o </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use barcode\">fa-barcode</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bars\">fa-bars</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bath\">fa-bath</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bathtub\">fa-bathtub </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use battery\">fa-battery </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use battery-0\">fa-battery-0 </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use battery-1\">fa-battery-1 </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use battery-2\">fa-battery-2 </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use battery-3\">fa-battery-3 </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use battery-4\">fa-battery-4 </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use battery-empty\">fa-battery-empty</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use battery-full\">fa-battery-full</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use battery-half\">fa-battery-half</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use battery-quarter\">fa-battery-quarter</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use battery-three-quarters\">fa-battery-three-quarters</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bed\">fa-bed</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use beer\">fa-beer</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use behance\">fa-behance</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use behance-square\">fa-behance-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bell\">fa-bell</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bell-o\">fa-bell-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bell-slash\">fa-bell-slash</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bell-slash-o\">fa-bell-slash-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bicycle\">fa-bicycle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use binoculars\">fa-binoculars</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use birthday-cake\">fa-birthday-cake</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bitbucket\">fa-bitbucket</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bitbucket-square\">fa-bitbucket-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bitcoin\">fa-bitcoin </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use black-tie\">fa-black-tie</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use blind\">fa-blind</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bluetooth\">fa-bluetooth</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bluetooth-b\">fa-bluetooth-b</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bold\">fa-bold</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bolt\">fa-bolt</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bomb\">fa-bomb</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use book\">fa-book</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bookmark\">fa-bookmark</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bookmark-o\">fa-bookmark-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use braille\">fa-braille</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use briefcase\">fa-briefcase</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use btc\">fa-btc</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bug\">fa-bug</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use building\">fa-building</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use building-o\">fa-building-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bullhorn\">fa-bullhorn</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bullseye\">fa-bullseye</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use bus\">fa-bus</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use buysellads\">fa-buysellads</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cab\">fa-cab </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use calculator\">fa-calculator</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use calendar\">fa-calendar</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use calendar-check-o\">fa-calendar-check-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use calendar-minus-o\">fa-calendar-minus-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use calendar-o\">fa-calendar-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use calendar-plus-o\">fa-calendar-plus-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use calendar-times-o\">fa-calendar-times-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use camera\">fa-camera</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use camera-retro\">fa-camera-retro</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use car\">fa-car</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use caret-down\">fa-caret-down</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use caret-left\">fa-caret-left</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use caret-right\">fa-caret-right</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use caret-square-o-down\">fa-caret-square-o-down</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use caret-square-o-left\">fa-caret-square-o-left</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use caret-square-o-right\">fa-caret-square-o-right</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use caret-square-o-up\">fa-caret-square-o-up</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use caret-up\">fa-caret-up</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cart-arrow-down\">fa-cart-arrow-down</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cart-plus\">fa-cart-plus</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cc\">fa-cc</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cc-amex\">fa-cc-amex</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cc-diners-club\">fa-cc-diners-club</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cc-discover\">fa-cc-discover</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cc-jcb\">fa-cc-jcb</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cc-mastercard\">fa-cc-mastercard</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cc-paypal\">fa-cc-paypal</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cc-stripe\">fa-cc-stripe</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cc-visa\">fa-cc-visa</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use certificate\">fa-certificate</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use chain\">fa-chain </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use chain-broken\">fa-chain-broken</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use check\">fa-check</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use check-circle\">fa-check-circle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use check-circle-o\">fa-check-circle-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use check-square\">fa-check-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use check-square-o\">fa-check-square-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use chevron-circle-down\">fa-chevron-circle-down</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use chevron-circle-left\">fa-chevron-circle-left</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use chevron-circle-right\">fa-chevron-circle-right</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use chevron-circle-up\">fa-chevron-circle-up</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use chevron-down\">fa-chevron-down</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use chevron-left\">fa-chevron-left</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use chevron-right\">fa-chevron-right</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use chevron-up\">fa-chevron-up</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use child\">fa-child</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use chrome\">fa-chrome</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use circle\">fa-circle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use circle-o\">fa-circle-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use circle-o-notch\">fa-circle-o-notch</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use circle-thin\">fa-circle-thin</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use clipboard\">fa-clipboard</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use clock-o\">fa-clock-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use clone\">fa-clone</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use close\">fa-close </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cloud\">fa-cloud</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cloud-download\">fa-cloud-download</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cloud-upload\">fa-cloud-upload</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cny\">fa-cny </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use code\">fa-code</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use code-fork\">fa-code-fork</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use codepen\">fa-codepen</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use codiepie\">fa-codiepie</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use coffee\">fa-coffee</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cog\">fa-cog</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cogs\">fa-cogs</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use columns\">fa-columns</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use comment\">fa-comment</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use comment-o\">fa-comment-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use commenting\">fa-commenting</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use commenting-o\">fa-commenting-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use comments\">fa-comments</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use comments-o\">fa-comments-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use compass\">fa-compass</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use compress\">fa-compress</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use connectdevelop\">fa-connectdevelop</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use contao\">fa-contao</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use copy\">fa-copy </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use copyright\">fa-copyright</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use creative-commons\">fa-creative-commons</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use credit-card\">fa-credit-card</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use credit-card-alt\">fa-credit-card-alt</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use crop\">fa-crop</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use crosshairs\">fa-crosshairs</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use css3\">fa-css3</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cube\">fa-cube</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cubes\">fa-cubes</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cut\">fa-cut </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use cutlery\">fa-cutlery</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use dashboard\">fa-dashboard </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use dashcube\">fa-dashcube</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use database\">fa-database</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use deaf\">fa-deaf</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use deafness\">fa-deafness </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use dedent\">fa-dedent </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use delicious\">fa-delicious</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use desktop\">fa-desktop</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use deviantart\">fa-deviantart</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use diamond\">fa-diamond</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use digg\">fa-digg</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use dollar\">fa-dollar </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use dot-circle-o\">fa-dot-circle-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use download\">fa-download</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use dribbble\">fa-dribbble</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use drivers-license\">fa-drivers-license </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use drivers-license-o\">fa-drivers-license-o </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use dropbox\">fa-dropbox</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use drupal\">fa-drupal</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use edge\">fa-edge</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use edit\">fa-edit </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use eercast\">fa-eercast</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use eject\">fa-eject</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use ellipsis-h\">fa-ellipsis-h</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use ellipsis-v\">fa-ellipsis-v</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use empire\">fa-empire</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use envelope\">fa-envelope</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use envelope-o\">fa-envelope-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use envelope-open\">fa-envelope-open</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use envelope-open-o\">fa-envelope-open-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use envelope-square\">fa-envelope-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use envira\">fa-envira</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use eraser\">fa-eraser</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use etsy\">fa-etsy</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use eur\">fa-eur</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use euro\">fa-euro </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use exchange\">fa-exchange</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use exclamation\">fa-exclamation</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use exclamation-circle\">fa-exclamation-circle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use exclamation-triangle\">fa-exclamation-triangle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use expand\">fa-expand</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use expeditedssl\">fa-expeditedssl</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use external-link\">fa-external-link</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use external-link-square\">fa-external-link-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use eye\">fa-eye</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use eye-slash\">fa-eye-slash</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use eyedropper\">fa-eyedropper</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use fa\">fa-fa </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use facebook\">fa-facebook</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use facebook-f\">fa-facebook-f </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use facebook-official\">fa-facebook-official</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use facebook-square\">fa-facebook-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use fast-backward\">fa-fast-backward</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use fast-forward\">fa-fast-forward</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use fax\">fa-fax</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use feed\">fa-feed </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use female\">fa-female</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use fighter-jet\">fa-fighter-jet</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use file\">fa-file</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use file-archive-o\">fa-file-archive-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use file-audio-o\">fa-file-audio-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use file-code-o\">fa-file-code-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use file-excel-o\">fa-file-excel-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use file-image-o\">fa-file-image-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use file-movie-o\">fa-file-movie-o </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use file-o\">fa-file-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use file-pdf-o\">fa-file-pdf-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use file-photo-o\">fa-file-photo-o </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use file-picture-o\">fa-file-picture-o </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use file-powerpoint-o\">fa-file-powerpoint-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use file-sound-o\">fa-file-sound-o </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use file-text\">fa-file-text</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use file-text-o\">fa-file-text-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use file-video-o\">fa-file-video-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use file-word-o\">fa-file-word-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use file-zip-o\">fa-file-zip-o </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use files-o\">fa-files-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use film\">fa-film</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use filter\">fa-filter</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use fire\">fa-fire</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use fire-extinguisher\">fa-fire-extinguisher</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use firefox\">fa-firefox</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use first-order\">fa-first-order</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use flag\">fa-flag</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use flag-checkered\">fa-flag-checkered</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use flag-o\">fa-flag-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use flash\">fa-flash </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use flask\">fa-flask</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use flickr\">fa-flickr</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use floppy-o\">fa-floppy-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use folder\">fa-folder</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use folder-o\">fa-folder-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use folder-open\">fa-folder-open</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use folder-open-o\">fa-folder-open-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use font\">fa-font</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use font-awesome\">fa-font-awesome</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use fonticons\">fa-fonticons</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use fort-awesome\">fa-fort-awesome</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use forumbee\">fa-forumbee</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use forward\">fa-forward</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use foursquare\">fa-foursquare</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use free-code-camp\">fa-free-code-camp</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use frown-o\">fa-frown-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use futbol-o\">fa-futbol-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use gamepad\">fa-gamepad</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use gavel\">fa-gavel</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use gbp\">fa-gbp</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use ge\">fa-ge </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use gear\">fa-gear </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use gears\">fa-gears </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use genderless\">fa-genderless</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use get-pocket\">fa-get-pocket</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use gg\">fa-gg</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use gg-circle\">fa-gg-circle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use gift\">fa-gift</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use git\">fa-git</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use git-square\">fa-git-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use github\">fa-github</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use github-alt\">fa-github-alt</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use github-square\">fa-github-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use gitlab\">fa-gitlab</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use gittip\">fa-gittip </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use glass\">fa-glass</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use glide\">fa-glide</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use glide-g\">fa-glide-g</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use globe\">fa-globe</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use google\">fa-google</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use google-plus\">fa-google-plus</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use google-plus-circle\">fa-google-plus-circle </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use google-plus-official\">fa-google-plus-official</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use google-plus-square\">fa-google-plus-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use google-wallet\">fa-google-wallet</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use graduation-cap\">fa-graduation-cap</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use gratipay\">fa-gratipay</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use grav\">fa-grav</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use group\">fa-group </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use h-square\">fa-h-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hacker-news\">fa-hacker-news</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hand-grab-o\">fa-hand-grab-o </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hand-lizard-o\">fa-hand-lizard-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hand-o-down\">fa-hand-o-down</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hand-o-left\">fa-hand-o-left</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hand-o-right\">fa-hand-o-right</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hand-o-up\">fa-hand-o-up</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hand-paper-o\">fa-hand-paper-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hand-peace-o\">fa-hand-peace-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hand-pointer-o\">fa-hand-pointer-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hand-rock-o\">fa-hand-rock-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hand-scissors-o\">fa-hand-scissors-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hand-spock-o\">fa-hand-spock-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hand-stop-o\">fa-hand-stop-o </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use handshake-o\">fa-handshake-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hard-of-hearing\">fa-hard-of-hearing </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hashtag\">fa-hashtag</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hdd-o\">fa-hdd-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use header\">fa-header</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use headphones\">fa-headphones</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use heart\">fa-heart</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use heart-o\">fa-heart-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use heartbeat\">fa-heartbeat</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use history\">fa-history</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use home\">fa-home</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hospital-o\">fa-hospital-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hotel\">fa-hotel </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hourglass\">fa-hourglass</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hourglass-1\">fa-hourglass-1 </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hourglass-2\">fa-hourglass-2 </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hourglass-3\">fa-hourglass-3 </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hourglass-end\">fa-hourglass-end</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hourglass-half\">fa-hourglass-half</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hourglass-o\">fa-hourglass-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use hourglass-start\">fa-hourglass-start</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use houzz\">fa-houzz</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use html5\">fa-html5</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use i-cursor\">fa-i-cursor</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use id-badge\">fa-id-badge</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use id-card\">fa-id-card</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use id-card-o\">fa-id-card-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use ils\">fa-ils</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use image\">fa-image </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use imdb\">fa-imdb</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use inbox\">fa-inbox</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use indent\">fa-indent</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use industry\">fa-industry</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use info\">fa-info</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use info-circle\">fa-info-circle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use inr\">fa-inr</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use instagram\">fa-instagram</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use institution\">fa-institution </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use internet-explorer\">fa-internet-explorer</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use intersex\">fa-intersex </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use ioxhost\">fa-ioxhost</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use italic\">fa-italic</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use joomla\">fa-joomla</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use jpy\">fa-jpy</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use jsfiddle\">fa-jsfiddle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use key\">fa-key</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use keyboard-o\">fa-keyboard-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use krw\">fa-krw</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use language\">fa-language</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use laptop\">fa-laptop</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use lastfm\">fa-lastfm</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use lastfm-square\">fa-lastfm-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use leaf\">fa-leaf</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use leanpub\">fa-leanpub</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use legal\">fa-legal </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use lemon-o\">fa-lemon-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use level-down\">fa-level-down</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use level-up\">fa-level-up</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use life-bouy\">fa-life-bouy </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use life-buoy\">fa-life-buoy </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use life-ring\">fa-life-ring</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use life-saver\">fa-life-saver </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use lightbulb-o\">fa-lightbulb-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use line-chart\">fa-line-chart</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use link\">fa-link</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use linkedin\">fa-linkedin</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use linkedin-square\">fa-linkedin-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use linode\">fa-linode</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use linux\">fa-linux</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use list\">fa-list</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use list-alt\">fa-list-alt</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use list-ol\">fa-list-ol</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use list-ul\">fa-list-ul</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use location-arrow\">fa-location-arrow</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use lock\">fa-lock</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use long-arrow-down\">fa-long-arrow-down</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use long-arrow-left\">fa-long-arrow-left</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use long-arrow-right\">fa-long-arrow-right</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use long-arrow-up\">fa-long-arrow-up</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use low-vision\">fa-low-vision</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use magic\">fa-magic</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use magnet\">fa-magnet</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use mail-forward\">fa-mail-forward </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use mail-reply\">fa-mail-reply </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use mail-reply-all\">fa-mail-reply-all </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use male\">fa-male</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use map\">fa-map</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use map-marker\">fa-map-marker</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use map-o\">fa-map-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use map-pin\">fa-map-pin</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use map-signs\">fa-map-signs</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use mars\">fa-mars</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use mars-double\">fa-mars-double</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use mars-stroke\">fa-mars-stroke</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use mars-stroke-h\">fa-mars-stroke-h</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use mars-stroke-v\">fa-mars-stroke-v</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use maxcdn\">fa-maxcdn</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use meanpath\">fa-meanpath</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use medium\">fa-medium</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use medkit\">fa-medkit</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use meetup\">fa-meetup</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use meh-o\">fa-meh-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use mercury\">fa-mercury</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use microchip\">fa-microchip</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use microphone\">fa-microphone</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use microphone-slash\">fa-microphone-slash</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use minus\">fa-minus</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use minus-circle\">fa-minus-circle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use minus-square\">fa-minus-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use minus-square-o\">fa-minus-square-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use mixcloud\">fa-mixcloud</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use mobile\">fa-mobile</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use mobile-phone\">fa-mobile-phone </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use modx\">fa-modx</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use money\">fa-money</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use moon-o\">fa-moon-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use mortar-board\">fa-mortar-board </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use motorcycle\">fa-motorcycle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use mouse-pointer\">fa-mouse-pointer</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use music\">fa-music</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use navicon\">fa-navicon </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use neuter\">fa-neuter</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use newspaper-o\">fa-newspaper-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use object-group\">fa-object-group</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use object-ungroup\">fa-object-ungroup</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use odnoklassniki\">fa-odnoklassniki</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use odnoklassniki-square\">fa-odnoklassniki-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use opencart\">fa-opencart</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use openid\">fa-openid</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use opera\">fa-opera</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use optin-monster\">fa-optin-monster</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use outdent\">fa-outdent</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use pagelines\">fa-pagelines</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use paint-brush\">fa-paint-brush</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use paper-plane\">fa-paper-plane</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use paper-plane-o\">fa-paper-plane-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use paperclip\">fa-paperclip</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use paragraph\">fa-paragraph</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use paste\">fa-paste </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use pause\">fa-pause</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use pause-circle\">fa-pause-circle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use pause-circle-o\">fa-pause-circle-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use paw\">fa-paw</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use paypal\">fa-paypal</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use pencil\">fa-pencil</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use pencil-square\">fa-pencil-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use pencil-square-o\">fa-pencil-square-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use percent\">fa-percent</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use phone\">fa-phone</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use phone-square\">fa-phone-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use photo\">fa-photo </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use picture-o\">fa-picture-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use pie-chart\">fa-pie-chart</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use pied-piper\">fa-pied-piper</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use pied-piper-alt\">fa-pied-piper-alt</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use pied-piper-pp\">fa-pied-piper-pp</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use pinterest\">fa-pinterest</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use pinterest-p\">fa-pinterest-p</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use pinterest-square\">fa-pinterest-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use plane\">fa-plane</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use play\">fa-play</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use play-circle\">fa-play-circle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use play-circle-o\">fa-play-circle-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use plug\">fa-plug</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use plus\">fa-plus</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use plus-circle\">fa-plus-circle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use plus-square\">fa-plus-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use plus-square-o\">fa-plus-square-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use podcast\">fa-podcast</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use power-off\">fa-power-off</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use print\">fa-print</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use product-hunt\">fa-product-hunt</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use puzzle-piece\">fa-puzzle-piece</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use qq\">fa-qq</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use qrcode\">fa-qrcode</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use question\">fa-question</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use question-circle\">fa-question-circle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use question-circle-o\">fa-question-circle-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use quora\">fa-quora</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use quote-left\">fa-quote-left</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use quote-right\">fa-quote-right</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use ra\">fa-ra </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use random\">fa-random</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use ravelry\">fa-ravelry</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use rebel\">fa-rebel</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use recycle\">fa-recycle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use reddit\">fa-reddit</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use reddit-alien\">fa-reddit-alien</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use reddit-square\">fa-reddit-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use refresh\">fa-refresh</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use registered\">fa-registered</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use remove\">fa-remove </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use renren\">fa-renren</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use reorder\">fa-reorder </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use repeat\">fa-repeat</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use reply\">fa-reply</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use reply-all\">fa-reply-all</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use resistance\">fa-resistance </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use retweet\">fa-retweet</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use rmb\">fa-rmb </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use road\">fa-road</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use rocket\">fa-rocket</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use rotate-left\">fa-rotate-left </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use rotate-right\">fa-rotate-right </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use rouble\">fa-rouble </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use rss\">fa-rss</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use rss-square\">fa-rss-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use rub\">fa-rub</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use ruble\">fa-ruble </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use rupee\">fa-rupee </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use s15\">fa-s15 </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use safari\">fa-safari</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use save\">fa-save </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use scissors\">fa-scissors</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use scribd\">fa-scribd</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use search\">fa-search</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use search-minus\">fa-search-minus</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use search-plus\">fa-search-plus</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sellsy\">fa-sellsy</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use send\">fa-send </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use send-o\">fa-send-o </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use server\">fa-server</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use share\">fa-share</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use share-alt\">fa-share-alt</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use share-alt-square\">fa-share-alt-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use share-square\">fa-share-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use share-square-o\">fa-share-square-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use shekel\">fa-shekel </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sheqel\">fa-sheqel </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use shield\">fa-shield</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use ship\">fa-ship</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use shirtsinbulk\">fa-shirtsinbulk</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use shopping-bag\">fa-shopping-bag</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use shopping-basket\">fa-shopping-basket</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use shopping-cart\">fa-shopping-cart</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use shower\">fa-shower</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sign-in\">fa-sign-in</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sign-language\">fa-sign-language</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sign-out\">fa-sign-out</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use signal\">fa-signal</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use signing\">fa-signing </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use simplybuilt\">fa-simplybuilt</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sitemap\">fa-sitemap</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use skyatlas\">fa-skyatlas</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use skype\">fa-skype</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use slack\">fa-slack</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sliders\">fa-sliders</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use slideshare\">fa-slideshare</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use smile-o\">fa-smile-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use snapchat\">fa-snapchat</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use snapchat-ghost\">fa-snapchat-ghost</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use snapchat-square\">fa-snapchat-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use snowflake-o\">fa-snowflake-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use soccer-ball-o\">fa-soccer-ball-o </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sort\">fa-sort</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sort-alpha-asc\">fa-sort-alpha-asc</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sort-alpha-desc\">fa-sort-alpha-desc</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sort-amount-asc\">fa-sort-amount-asc</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sort-amount-desc\">fa-sort-amount-desc</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sort-asc\">fa-sort-asc</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sort-desc\">fa-sort-desc</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sort-down\">fa-sort-down </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sort-numeric-asc\">fa-sort-numeric-asc</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sort-numeric-desc\">fa-sort-numeric-desc</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sort-up\">fa-sort-up </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use soundcloud\">fa-soundcloud</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use space-shuttle\">fa-space-shuttle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use spinner\">fa-spinner</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use spoon\">fa-spoon</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use spotify\">fa-spotify</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use square\">fa-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use square-o\">fa-square-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use stack-exchange\">fa-stack-exchange</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use stack-overflow\">fa-stack-overflow</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use star\">fa-star</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use star-half\">fa-star-half</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use star-half-empty\">fa-star-half-empty </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use star-half-full\">fa-star-half-full </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use star-half-o\">fa-star-half-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use star-o\">fa-star-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use steam\">fa-steam</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use steam-square\">fa-steam-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use step-backward\">fa-step-backward</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use step-forward\">fa-step-forward</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use stethoscope\">fa-stethoscope</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sticky-note\">fa-sticky-note</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sticky-note-o\">fa-sticky-note-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use stop\">fa-stop</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use stop-circle\">fa-stop-circle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use stop-circle-o\">fa-stop-circle-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use street-view\">fa-street-view</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use strikethrough\">fa-strikethrough</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use stumbleupon\">fa-stumbleupon</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use stumbleupon-circle\">fa-stumbleupon-circle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use subscript\">fa-subscript</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use subway\">fa-subway</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use suitcase\">fa-suitcase</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use sun-o\">fa-sun-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use superpowers\">fa-superpowers</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use superscript\">fa-superscript</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use support\">fa-support </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use table\">fa-table</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use tablet\">fa-tablet</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use tachometer\">fa-tachometer</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use tag\">fa-tag</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use tags\">fa-tags</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use tasks\">fa-tasks</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use taxi\">fa-taxi</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use telegram\">fa-telegram</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use television\">fa-television</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use tencent-weibo\">fa-tencent-weibo</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use terminal\">fa-terminal</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use text-height\">fa-text-height</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use text-width\">fa-text-width</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use th\">fa-th</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use th-large\">fa-th-large</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use th-list\">fa-th-list</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use themeisle\">fa-themeisle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use thermometer\">fa-thermometer </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use thermometer-0\">fa-thermometer-0 </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use thermometer-1\">fa-thermometer-1 </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use thermometer-2\">fa-thermometer-2 </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use thermometer-3\">fa-thermometer-3 </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use thermometer-4\">fa-thermometer-4 </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use thermometer-empty\">fa-thermometer-empty</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use thermometer-full\">fa-thermometer-full</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use thermometer-half\">fa-thermometer-half</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use thermometer-quarter\">fa-thermometer-quarter</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use thermometer-three-quarters\">fa-thermometer-three-quarters</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use thumb-tack\">fa-thumb-tack</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use thumbs-down\">fa-thumbs-down</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use thumbs-o-down\">fa-thumbs-o-down</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use thumbs-o-up\">fa-thumbs-o-up</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use thumbs-up\">fa-thumbs-up</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use ticket\">fa-ticket</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use times\">fa-times</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use times-circle\">fa-times-circle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use times-circle-o\">fa-times-circle-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use times-rectangle\">fa-times-rectangle </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use times-rectangle-o\">fa-times-rectangle-o </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use tint\">fa-tint</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use toggle-down\">fa-toggle-down </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use toggle-left\">fa-toggle-left </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use toggle-off\">fa-toggle-off</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use toggle-on\">fa-toggle-on</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use toggle-right\">fa-toggle-right </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use toggle-up\">fa-toggle-up </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use trademark\">fa-trademark</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use train\">fa-train</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use transgender\">fa-transgender</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use transgender-alt\">fa-transgender-alt</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use trash\">fa-trash</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use trash-o\">fa-trash-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use tree\">fa-tree</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use trello\">fa-trello</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use tripadvisor\">fa-tripadvisor</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use trophy\">fa-trophy</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use truck\">fa-truck</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use try\">fa-try</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use tty\">fa-tty</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use tumblr\">fa-tumblr</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use tumblr-square\">fa-tumblr-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use turkish-lira\">fa-turkish-lira </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use tv\">fa-tv </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use twitch\">fa-twitch</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use twitter\">fa-twitter</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use twitter-square\">fa-twitter-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use umbrella\">fa-umbrella</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use underline\">fa-underline</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use undo\">fa-undo</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use universal-access\">fa-universal-access</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use university\">fa-university</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use unlink\">fa-unlink </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use unlock\">fa-unlock</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use unlock-alt\">fa-unlock-alt</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use unsorted\">fa-unsorted </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use upload\">fa-upload</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use usb\">fa-usb</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use usd\">fa-usd</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use user\">fa-user</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use user-circle\">fa-user-circle</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use user-circle-o\">fa-user-circle-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use user-md\">fa-user-md</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use user-o\">fa-user-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use user-plus\">fa-user-plus</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use user-secret\">fa-user-secret</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use user-times\">fa-user-times</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use users\">fa-users</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use vcard\">fa-vcard </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use vcard-o\">fa-vcard-o </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use venus\">fa-venus</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use venus-double\">fa-venus-double</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use venus-mars\">fa-venus-mars</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use viacoin\">fa-viacoin</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use viadeo\">fa-viadeo</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use viadeo-square\">fa-viadeo-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use video-camera\">fa-video-camera</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use vimeo\">fa-vimeo</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use vimeo-square\">fa-vimeo-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use vine\">fa-vine</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use vk\">fa-vk</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use volume-control-phone\">fa-volume-control-phone</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use volume-down\">fa-volume-down</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use volume-off\">fa-volume-off</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use volume-up\">fa-volume-up</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use warning\">fa-warning </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use wechat\">fa-wechat </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use weibo\">fa-weibo</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use weixin\">fa-weixin</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use whatsapp\">fa-whatsapp</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use wheelchair\">fa-wheelchair</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use wheelchair-alt\">fa-wheelchair-alt</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use wifi\">fa-wifi</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use wikipedia-w\">fa-wikipedia-w</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use window-close\">fa-window-close</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use window-close-o\">fa-window-close-o</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use window-maximize\">fa-window-maximize</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use window-minimize\">fa-window-minimize</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use window-restore\">fa-window-restore</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use windows\">fa-windows</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use won\">fa-won </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use wordpress\">fa-wordpress</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use wpbeginner\">fa-wpbeginner</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use wpexplorer\">fa-wpexplorer</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use wpforms\">fa-wpforms</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use wrench\">fa-wrench</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use xing\">fa-xing</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use xing-square\">fa-xing-square</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use y-combinator\">fa-y-combinator</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use y-combinator-square\">fa-y-combinator-square </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use yahoo\">fa-yahoo</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use yc\">fa-yc </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use yc-square\">fa-yc-square </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use yelp\">fa-yelp</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use yen\">fa-yen </i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use yoast\">fa-yoast</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use youtube\">fa-youtube</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use youtube-play\">fa-youtube-play</i>",
            "<i class=".$class." aria-hidden=\"true\" title=\"Copy to use youtube-square\">fa-youtube-square</i>"
        ];
        for($i = 0; $i < count($array);$i++)
        {
            $description = explode('<',explode('>', $array[$i],141)[1],38)[0];
            $this->view_data['icons'] [] = ['class' => $class, 'html'=>$array[$i], 'description'=>$description];
        }

        $html_placeholders = [];
        $html_placeholders[] = new DefaultPlaceholder('{{Title}}', '', 'Lista di icone con font Awesome');

        // get html view and run it inside backend html structure
        $this->addHtmlFileToView($this, 'FontAwesome.html.php');
        $this->replaceThePlaceholder($html_placeholders);
        $html = $this->getBaseView();
        $this->backend->run($this->title, '', '', $html, '', '', 1);
    }
}
